version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Puerto de RabbitMQ para la comunicación con la aplicación
      - "15672:15672"    # Puerto de la interfaz de administración de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  app:
    build: .
    container_name: app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672  # URL de conexión a RabbitMQ
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    command: npx ts-node -r tsconfig-paths/register src/app.ts

  consumer:
    build: .
    container_name: consumer
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672  # URL de conexión a RabbitMQ
    depends_on:
      - rabbitmq
    command: npx ts-node -r tsconfig-paths/register src/consumers/identityValidator.ts

volumes:
  mongo_data:

